<?php
/*
 *
 *
 *	This Codeigniter controller file is automatically generated by Code Generator.
 * 	Filename 		: 	Users.php
 * 	Generated 		: 	03-31-2018|14:09:42
 **/
defined('BASEPATH') OR exit ('No direct script to access allowed');

class Users_service extends CI_Controller 
{ 
	public function save()
	{ 
		try 
		{ 
			$this->load->model('Users_model','model');

			$this->model->Position_ID	=	$this->input->post('Position_ID');
			$this->model->First_name	=	$this->input->post('First_name');
			$this->model->Last_name	=	$this->input->post('Last_name');
			$this->model->Username	=	$this->input->post('Username');
			$this->model->Password	=	$this->input->post('Password');
			$this->model->Salt	=	$this->input->post('Salt');

			if($this->input->post('ID') == '' || $this->input->post('ID')==0)
			{ 
				$this->model->save(); 
			} 
			else 
			{ 
				$this->model->ID = $this->input->post('ID'); 
				$this->model->save(); 
			} 
		} 
		catch(Exception $ex) 
		{ 
			echo $ex->getMessage();
		} 
	} 

	public function save_module()
	{
		try
		{	
			$this->load->model('Users_model', 'users');
			
			$this->users->ID = $this->input->post('User_ID');
			$this->users->Module_ID = $this->input->post('Module_ID');
			$this->users->Restrict_access = $this->input->post('Restrict_access');
			$this->users->Full_control = $this->input->post('Full_control');
			$this->users->Read_only = $this->input->post('Read_only');
			$this->users->Write_only = $this->input->post('Write_only');
			
			$this->users->save_user_module();
		}
		catch(Exception $ex)
		{
			echo $ex->getMessage();
		}
	}

	public function delete($id)
	{ 
		try 
		{ 
			$this->load->model('Users_model','model');
			$this->model->delete($id); 
		} 
		catch(Exception $ex) 
		{ 
			echo $ex->getMessage();
		} 
	} 

	public function reset_password()
	{
		try 
		{ 
			$this->load->model('Users_model','model');
			$this->model->ID = $this->input->post('ID');

			$this->model->reset_password(); 
		} 
		catch(Exception $ex) 
		{ 
			echo $ex->getMessage();
		} 
	}

	public function change_password()
	{
		try 
		{ 
			$this->load->model('Users_model','model');
			$this->model->ID = $this->input->post('ID');
			$this->model->password = $this->input->post('password');

			$this->model->change_password(); 
		} 
		catch(Exception $ex) 
		{ 
			echo $ex->getMessage();
		} 
	}

	public function getSingle($id)
	{ 
		try 
		{ 
			$this->load->model('Users_model','model');
			$result = $this->model->getSingle($id); 

			echo json_encode($result);
		} 
		catch(Exception $ex) 
		{ 
			echo $ex->getMessage();
		} 
	} 

	public function getAll($search = '')
	{ 
		try 
		{ 
			$this->load->model('Users_model','model');
			$result = $this->model->getAll($search); 

			echo json_encode($result);
		} 
		catch(Exception $ex) 
		{ 
			echo $ex->getMessage();
		} 
	} 

	public function authenticate(){
        try
        {
            $this->load->model('users/Users_model', 'model');
            $username = $this->input->post('Username',TRUE);
            $password = $this->input->post('Password',TRUE);

            $this->model->authenticate_user($username,$password);
        }
        catch(Exception $ex)
        {
            echo $ex->getMessage();
        }
	}
	
	public function service_online(){
		//to be change

		try{
			// var_dump($this->input->post('status',true));
			
			$temp = filter_var( $this->input->post('status',true), FILTER_VALIDATE_BOOLEAN);
			$this->session->set_userdata('service_status',(int)$temp);
		
			// var_dump($this->session->userdata('service_status'));
			$response = array('has_error' => false, 'status' => $this->session->userdata('service_status'));
			echo json_encode($response);
		}  catch(Exception $ex)
        {
            echo $ex->getMessage();
        }
	}
}